# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c950bc5b0f81b117e6b8ebcd81bf78bca156ed7eb3fbcd59b5b4c7b0e4fb9f5a92a7f7771e7801bba88c2154489d79851a396b9f7f7615cb909f56e000166ba

test:
  secret_key_base: 840f9a101d676385c513ebb74ec80b14c0fd22333737e1d9dfa4b1ee786f6d95fb8297c6e0c0ff09e48acf228602ac5273a118a972b8bfab0c2e5e1d6779ae4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
